### ISSUE TITLE
Should not translate URL

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/integration_documenso#2]
https://github.com/nextcloud/integration_documenso/blob/12311f2e5b9e1c6af80956c2e4552e85fe9a4499/src/components/PersonalSettings.vue#L20

Instead use plain text?
```
placeholder="https://app.documenso.com/"
```

**Comment by janepie** [comment]
Thank you for spotting this! Fixed in 8315f388aaa87e75c2efd8b6d6ddb8dfd28bbbf6
